version: '3'

services:
  api:
    build: .
    # restart: unless-stopped
    volumes:
      - ./data:/data
      - .:/srv/app
    environment:
      # - RACK_ENV=production
      - URL_BASE=https://a.short.com
      - STORAGE_PATH=/data
    ports:
      - "8635:8635"
