version: '3'

services:
  api:
    build: .
    image: ghcr.io/teritorio/qr-shortener:master
    volumes:
      - ./data:/data
    environment:
      RACK_ENV: ${RACK_ENV}
      URL_BASE: ${URL_BASE:-https://a.short.com}
      STORAGE_PATH: /data
    ports:
      - "8635:8635"
    restart: unless-stopped
